list: $/yfktn/suratmasuk/models/suratmasuk/columns.yaml
modelClass: Yfktn\SuratMasuk\Models\SuratMasuk
title: SuratMasuk
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'yfktn/suratmasuk/suratmasuk/update/:id'
filter: config_filter.yaml
