plugin:
    name: 'yfktn.suratmasuk::lang.plugin.name'
    description: 'yfktn.suratmasuk::lang.plugin.description'
    author: yfktn
    icon: oc-icon-inbox
    homepage: ''
permissions:
    yfktn.surat_masuk.management:
        tab: 'Surat Masuk'
        label: 'Manajemen Surat Masuk'
navigation:
    main-menu-suratmasuk:
        label: 'Surat Masuk'
        url: yfktn/suratmasuk/suratmasuk
        icon: icon-inbox
        permissions:
            - yfktn.surat_masuk.management
